version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: weekly
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: weekly