version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: dayliy
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: daily