name: shirasu
description: A unofficial client app for SHIRASU

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.3
repository: https://github.com/HiroyukTamura/shirasu

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # flutter, dart official
  async: ^2.4.2
  cached_network_image: ^2.5.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl:
  http: ^0.12.2
  crypto: ^2.1.5
  # google
  json_annotation: ^3.1.0
  tuple: ^1.0.3
  # Remi
  freezed_annotation: ^0.12.0
  hooks_riverpod: ^0.12.3
  flutter_hooks: ^0.15.0
  # flutter community
  after_layout: ^1.0.7+2
  connectivity: ^2.0.2
  url_launcher: ^5.7.10
  flutter_webview_plugin: ^0.3.11
  font_awesome_flutter: ^8.11.0
  material_design_icons_flutter: 4.0.5855
  # firebase
  firebase_core: ^0.7.0
  firebase_crashlytics: ^0.4.0+1
  firebase_analytics: ^7.0.1
  firebase_performance: ^0.5.0+1
  firebase_messaging: "^8.0.0-dev.15"
  # hive
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  #dio
  dio: ^3.0.10
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1

  # others
  background_fetch: ^0.7.1
  app_settings: ^4.1.0
  flutter_secure_storage: ^4.1.0
  flutter_inappwebview: ^5.1.0+4
  flutter_keyboard_visibility: ^4.0.4
  introduction_screen: ^1.0.9
  flutter_svg: 0.19.3
  graphql_flutter: ^4.0.1
  flutter_linkify: ^4.0.2
  jwt_decoder: ^2.0.0
  rounded_loading_button: ^1.0.18
  email_validator: ^2.0.1
  tab_indicator_styler: ^1.0.0
  smooth_page_indicator: ^0.2.0
  synchronized: ^2.2.0+2
  functional_widget_annotation: ^0.8.0
  sliding_up_panel: ^1.0.2
  dartx: ^0.5.0
  better_player: ^0.0.60
  circular_reveal_animation: ^1.1.5
  flutter_custom_clippers: ^1.1.2
  double_tap_player_view: ^1.0.6
  lottie: ^0.7.0+1
  uuid: ^2.2.2
  simple_animations: ^2.5.1
  flutter_video_background:
    git: https://github.com/HiroyukTamura/flutter_video_background


dev_dependencies:
  hive_generator: ^0.8.2
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test: ^1.0.0
  golden_toolkit: ^0.8.0
  test: ^1.15.4
  build_runner: ^1.11.1
  freezed: ^0.12.7
  json_serializable: ^3.5.1
  functional_widget: ^0.8.1
  flutter_launcher_icons: "^0.8.0" # needs quotes @see https://github.com/fluttercommunity/flutter_launcher_icons/issues/220
  grinder: ^0.8.6


flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_logo.png"

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpeg/
    - assets/svg/
    - assets/json/
    - assets/lottie/
    - assets/js/
