name: shirasu
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  async: ^2.4.2
  http: ^0.12.2
  url_launcher: ^5.7.10
  cached_network_image: ^2.3.3
  flutter_webview_plugin: ^0.3.11
  webview_flutter: ^1.0.7
  font_awesome_flutter: ^8.10.0
  material_design_icons_flutter: 4.0.5755
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  introduction_screen: ^1.0.9
  flutter_svg: ^0.19.1
  graphql_flutter: ^4.0.0-beta.5
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.0
  hooks_riverpod: ^0.12.1
  flutter_hooks: ^0.15.0
  intl:
  flutter_linkify: ^4.0.2
  dio: ^3.0.10
  google_fonts: ^1.1.1
  tuple: ^1.0.3
  tab_indicator_styler: ^1.0.0
  smooth_page_indicator: ^0.2.0
  synchronized: ^2.2.0+2
  after_layout: ^1.0.7+2
  functional_widget_annotation: ^0.8.0
  quiver: ^2.1.5
  sliding_up_panel: ^1.0.2
  dartx: ^0.5.0
  flutter_playout:
    git:
      url: https://github.com/HiroyukTamura/flutter_playout.git
      ref: 9d839213e9d8b2ddd64b76b270ca19c9b0a35176

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.8.2
  test: ^1.15.4
  build_runner: ^1.10.4
  freezed: ^0.12.2
  json_serializable: ^3.5.0
  functional_widget: ^0.8.1
  flutter_launcher_icons: "^0.8.0" # needs quotes @see https://github.com/fluttercommunity/flutter_launcher_icons/issues/220

flutter_icons:
  android: true
  ios: true
  image_path: "assets/png/app_logo.png"


flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/jpeg/
    - assets/svg/
    - assets/json/
    - assets/js/
