name: lp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0-259.16.beta <3.0.0'

dependencies:
#  firebase_analytics: ^7.1.1 not null safety yet
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: 1.0.1
  flutter_hooks: ^0.16.0-nullsafety.0
  hooks_riverpod: ^0.13.1
  dartx: ^0.6.0
  freezed_annotation: ^0.14.0
  flutter_svg: ^0.21.0-nullsafety.0
  google_fonts: ^2.0.0
  font_awesome_flutter: ^9.0.0-nullsafety
  functional_widget_annotation: ^0.8.0
  url_launcher: ^6.0.2
  sentry_flutter: ^4.1.0-nullsafety.0
  scroll_to_index: any

dev_dependencies:
  build_runner: ^1.11.1
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0
  freezed: ^0.14.0
  functional_widget: ^0.8.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  fonts:
    - family: Shingo
      fonts:
        - asset: fonts/TT-UDShinGoPro-Medium.ttf
        - asset: fonts/TT-UDShinGoPro-Bold.ttf
          weight: 700
    - family: NotoSansJp
      fonts:
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Bold.otf
          weight: 700
  assets:
    - assets/svg/
    - assets/png/