name: FlutterAnalyzer

on:
  push:
    branches:
      - dev_temp

jobs:
  flutter_analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze --fatal-infos

  android_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Inspection
      working-directory: ./android
      run: ./gradlew lint
      - name: Upload results Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: results
          path: |
            **/build/reports/lint-results.html
            **/build/reports/lint-results.xml
          if-no-files-found: error
          retention-days: 14